### ISSUE TITLE
blessy's to do list

### ISSUE THREAD

**Issue by blessyperumal** [scatrin/sep-22-developers#2]
## To Do List

- [x] Create an issue
- [ ] Create a branch
- [ ] Edit files locally and push it
- [ ] Create a Pull req
- [ ] Edit files GitHub.com and pull it
- [ ] Merge a Pull req
- [ ] A calm Christmas? 

:christmas_tree: :santa: :+1:

**Comment by p-3** [comment]
:package: with :cookie:  :+1:
